In [9]:
library(fs)

# Set directories
home_dir <- Sys.getenv("HOME")
repo_dir <- file.path(home_dir, "OneDrive/git-repos/LCBP-interannual-EMMAs")

source(file.path(repo_dir, "Functions/calculate_tracer_rrmse_table.R"))

data_dir  <- file.path(repo_dir, "Data/")
chem_file <- file.path(data_dir, "GrabSample_data", "RI23-IC-ICP-isotope-toc-joined.csv")

# 1. Generate Table 3 for Hungerford Brook (1-6 dimensions)

hungerford_tracers <- c("Mn_mg_L", "Ca_mg_L", "Mg_mg_L", "Na_mg_L", "Cl_mg_L", "Si_mg_L", "dD", "d18O", "SO4_mg_L", "K_mg_L", "Cu_mg_L", "P_mg_L")

hungerford_table3 <- calculate_tracer_rrmse_table(
  chem_data_file   = chem_file,
  site_name        = "Hungerford",
  max_dims         = 6,
  selected_tracers = hungerford_tracers
)
print("=== Table S2: Hungerford Brook RRMSE Projection of streamwater observations in a mixing space created by its own eigenvectors (1-6) ===")
print(hungerford_table3)

# 2. Generate Table 3 for Wade Brook (1-6 dimensions)

wade_tracers <- c("Mn_mg_L","Cu_mg_L", "P_mg_L", "Cl_mg_L", "SO4_mg_L", "Ca_mg_L", "Mg_mg_L", "Na_mg_L", "dD", "d18O", "DOC_mg_L", "K_mg_L")

wade_table3 <- calculate_tracer_rrmse_table(
  chem_data_file   = chem_file,
  site_name        = "Wade",
  max_dims         = 6,
  selected_tracers = wade_tracers
)
print("=== Table S3: Wade Brook RRMSE Projection of streamwater observations in a mixing space created by its own eigenvectors (1-6) ===")
print(wade_table3)

ℹ️ Site: Hungerford | Computing RRMSE for dimensions 1 to 6 across n = 25 complete samples (12 tracers)

[1] "=== Table S2: Hungerford Brook RRMSE Projection of streamwater observations in a mixing space created by its own eigenvectors (1-6) ==="
# A tibble: 12 × 9
   Site       Tracer   N_Samples    m_1    m_2    m_3    m_4     m_5     m_6
   <chr>      <chr>        <int>  <dbl>  <dbl>  <dbl>  <dbl>   <dbl>   <dbl>
 1 Hungerford Mn_mg_L         25 0.567  0.471  0.376  0.364  0.185   0.135
 2 Hungerford Ca_mg_L         25 0.122  0.0896 0.0869 0.0864 0.0835  0.0829
 3 Hungerford Mg_mg_L         25 0.0725 0.0591 0.0394 0.0318 0.0291  0.0234
 4 Hungerford Na_mg_L         25 0.0585 0.0481 0.0399 0.0330 0.0320  0.0279
 5 Hungerford Cl_mg_L         25 0.203  0.170  0.0963 0.0804 0.0376  0.0375
 6 Hungerford Si_mg_L         25 0.148  0.140  0.138  0.0569 0.0568  0.0242
 7 Hungerford dD              25 0.0303 0.0192 0.0139 0.0138 0.00649 0.00630
 8 Hungerford d18O            25 0.0310 0.0250 0.0170 0.0165 0.00650 0.00555
 9 Hungerford SO4_mg_L        25 0.256  0.193  0.188  0.145  0.145   0.137
10 Hungerford K_mg_L          25 0.232  0.0896 0.0839 0.0836 0.0477  0.0474
11 Hungerford Cu_mg_L         25 0.681  0.494  0.494  0.399  0.346   0.183
12 Hungerford P_mg_L          25 0.599  0.357  0.254  0.144  0.139   0.0786

ℹ️ Site: Wade | Computing RRMSE for dimensions 1 to 6 across n = 42 complete samples (12 tracers)

[1] "=== Table S3: Wade Brook RRMSE Projection of streamwater observations in a mixing space created by its own eigenvectors (1-6) ==="
# A tibble: 12 × 9
   Site  Tracer   N_Samples    m_1    m_2    m_3     m_4     m_5     m_6
   <chr> <chr>        <int>  <dbl>  <dbl>  <dbl>   <dbl>   <dbl>   <dbl>
 1 Wade  Mn_mg_L         42 0.840  0.489  0.319  0.312   0.309   0.301
 2 Wade  Cu_mg_L         42 0.880  0.553  0.476  0.471   0.313   0.272
 3 Wade  P_mg_L          42 0.316  0.164  0.103  0.0916  0.0890  0.0889
 4 Wade  Cl_mg_L         42 0.194  0.158  0.123  0.0478  0.0419  0.0209
 5 Wade  SO4_mg_L        42 0.355  0.225  0.157  0.116   0.0814  0.0704
 6 Wade  Ca_mg_L         42 0.112  0.0818 0.0442 0.0335  0.0286  0.0241
 7 Wade  Mg_mg_L         42 0.113  0.0847 0.0443 0.0387  0.0360  0.0338
 8 Wade  Na_mg_L         42 0.163  0.137  0.0917 0.0813  0.0803  0.0678
 9 Wade  dD              42 0.0253 0.0178 0.0153 0.00656 0.00652 0.00593
10 Wade  d18O            42 0.0332 0.0249 0.0222 0.00918 0.00838 0.00468
11 Wade  DOC_mg_L        42 0.192  0.192  0.0963 0.0940  0.0926  0.0577
12 Wade  K_mg_L          42 0.481  0.258  0.174  0.174   0.118   0.116

In [11]:
head(hungerford_table3)

  Site       Tracer  N_Samples m_1        m_2        m_3        m_4
1 Hungerford Mn_mg_L 25        0.56734056 0.47055846 0.37593600 0.36398923
2 Hungerford Ca_mg_L 25        0.12234682 0.08959536 0.08693641 0.08638519
3 Hungerford Mg_mg_L 25        0.07251342 0.05909187 0.03936829 0.03181775
4 Hungerford Na_mg_L 25        0.05846503 0.04809795 0.03985648 0.03300479
5 Hungerford Cl_mg_L 25        0.20286464 0.16963013 0.09628083 0.08038731
6 Hungerford Si_mg_L 25        0.14779878 0.13964699 0.13773447 0.05692978
  m_5        m_6
1 0.18519151 0.13522698
2 0.08350929 0.08285096
3 0.02913797 0.02338961
4 0.03195175 0.02786553
5 0.03763564 0.03751479
6 0.05677547 0.02420156

In [12]:
head(wade_table3)

  Site Tracer   N_Samples m_1       m_2        m_3        m_4        m_5
1 Wade Mn_mg_L  42        0.8400512 0.48855057 0.31896551 0.31226126 0.30875392
2 Wade Cu_mg_L  42        0.8797922 0.55306055 0.47616448 0.47141489 0.31272802
3 Wade P_mg_L   42        0.3161434 0.16389547 0.10251270 0.09158252 0.08897229
4 Wade Cl_mg_L  42        0.1941863 0.15812381 0.12255723 0.04782659 0.04191399
5 Wade SO4_mg_L 42        0.3545260 0.22522049 0.15686403 0.11550682 0.08137565
6 Wade Ca_mg_L  42        0.1120151 0.08175598 0.04417859 0.03349195 0.02860035
  m_6
1 0.30130968
2 0.27224951
3 0.08892778
4 0.02090278
5 0.07043346
6 0.02405698