In [3]:
library(fs)

# Set directories
home_dir <- Sys.getenv("HOME")
repo_dir <- file.path(home_dir, "OneDrive/git-repos/LCBP-interannual-EMMAs")

source(file.path(repo_dir, "Functions/calculate_tracer_rrmse_table.R"))

data_dir   <- file.path(repo_dir, "Data/")
chem_file  <- file.path(data_dir, "GrabSample_data", "RI23-IC-ICP-isotope-toc-joined.csv")
output_dir <- file.path(repo_dir, "Output/Tracer-selection/")

# 1. Generate & Save Table for Hungerford Brook
hungerford_tracers <- c("Mn_mg_L", "Ca_mg_L", "Mg_mg_L", "Na_mg_L", "Cl_mg_L", "Si_mg_L", "dD", "d18O", "SO4_mg_L", "K_mg_L", "Cu_mg_L", "P_mg_L")

hungerford_table3 <- calculate_tracer_rrmse_table(
  chem_data_file   = chem_file,
  site_name        = "Hungerford",
  max_dims         = 12,
  selected_tracers = hungerford_tracers,
  output_dir       = output_dir
)

# 2. Generate & Save Table for Wade Brook
wade_tracers <- c("Mn_mg_L", "Cu_mg_L", "P_mg_L", "Cl_mg_L", "SO4_mg_L", "Ca_mg_L", "Mg_mg_L", "Na_mg_L", "dD", "d18O", "DOC_mg_L", "K_mg_L")

wade_table3 <- calculate_tracer_rrmse_table(
  chem_data_file   = chem_file,
  site_name        = "Wade",
  max_dims         = 12,
  selected_tracers = wade_tracers,
  output_dir       = output_dir
)

ℹ️ Site: Hungerford | Computing RRMSE for dimensions 1 to 12 across n = 25 complete samples (12 tracers)

ℹ️ Site: Wade | Computing RRMSE for dimensions 1 to 12 across n = 42 complete samples (12 tracers)

In [4]:
head(hungerford_table3)

  Site       Tracer  N_Samples m_1        m_2        m_3        m_4
1 Hungerford Mn_mg_L 25        0.56734056 0.47055846 0.37593600 0.36398923
2 Hungerford Ca_mg_L 25        0.12234682 0.08959536 0.08693641 0.08638519
3 Hungerford Mg_mg_L 25        0.07251342 0.05909187 0.03936829 0.03181775
4 Hungerford Na_mg_L 25        0.05846503 0.04809795 0.03985648 0.03300479
5 Hungerford Cl_mg_L 25        0.20286464 0.16963013 0.09628083 0.08038731
6 Hungerford Si_mg_L 25        0.14779878 0.13964699 0.13773447 0.05692978
  m_5        m_6        m_7        m_8         m_9         m_10
1 0.18519151 0.13522698 0.13421940 0.018402298 0.018381925 0.008804296
2 0.08350929 0.08285096 0.04203796 0.023713857 0.004523985 0.002370548
3 0.02913797 0.02338961 0.02268930 0.022630476 0.016206299 0.015138461
4 0.03195175 0.02786553 0.02043043 0.018313022 0.017919181 0.017805894
5 0.03763564 0.03751479 0.03741924 0.011849330 0.011441343 0.010348104
6 0.05677547 0.02420156 0.01685511 0.004194397 0.003919674 0.003770957
  m_11         m_12
1 0.0031609233 9.505670e-16
2 0.0019401782 3.264173e-16
3 0.0074831901 2.122941e-16
4 0.0073563308 1.480184e-16
5 0.0099214400 4.064015e-16
6 0.0001991725 1.906136e-16

In [5]:
head(wade_table3)

  Site Tracer   N_Samples m_1       m_2        m_3        m_4        m_5
1 Wade Mn_mg_L  42        0.8400512 0.48855057 0.31896551 0.31226126 0.30875392
2 Wade Cu_mg_L  42        0.8797922 0.55306055 0.47616448 0.47141489 0.31272802
3 Wade P_mg_L   42        0.3161434 0.16389547 0.10251270 0.09158252 0.08897229
4 Wade Cl_mg_L  42        0.1941863 0.15812381 0.12255723 0.04782659 0.04191399
5 Wade SO4_mg_L 42        0.3545260 0.22522049 0.15686403 0.11550682 0.08137565
6 Wade Ca_mg_L  42        0.1120151 0.08175598 0.04417859 0.03349195 0.02860035
  m_6        m_7        m_8        m_9         m_10         m_11
1 0.30130968 0.27125970 0.08963777 0.035673084 0.0308607101 0.0035384064
2 0.27224951 0.03271199 0.03252000 0.021179867 0.0208635530 0.0063639708
3 0.08892778 0.07545659 0.06729920 0.052559483 0.0363050364 0.0019595553
4 0.02090278 0.01644830 0.01348089 0.006282726 0.0005663291 0.0001073166
5 0.07043346 0.04921850 0.03723718 0.012893878 0.0081546357 0.0009901377
6 0.02405698 0.01627522 0.01622460 0.016151302 0.0120845356 0.0095947508
  m_12
1 1.102256e-15
2 2.110946e-15
3 4.439853e-16
4 6.410676e-17
5 2.354256e-16
6 2.082206e-16