In [2]:
# Import libraries
library(fs)

# Set directories
home_dir <- Sys.getenv("HOME")
repo_dir <- file.path(home_dir, "OneDrive/git-repos/LCBP-interannual-EMMAs")
source(file.path(repo_dir, "Functions/plot_winter_air_temps.R"))
data_dir <- file.path(repo_dir, "Data/") 

# Setup for Hungerford winter 2023
target_site <- "Hungerford"
target_start <- "12-20-2022 00:00:00"
target_end <- "03-20-2023 00:00:00"
hungerford_file <- file.path(data_dir, "Met_data", "hungerford_2020-2024_met_2024-11-08.csv") 

# Run for Hungerford winter 2023
hungerford_winter_stats <- calculate_met_stats(
  site_name = target_site,
  start_datetime = target_start,
  end_datetime = target_end,
  met_data_path = hungerford_file
)

# View the results
head(hungerford_winter_stats)

New names:
• `` -> `...1`

  Site       Start_Time End_Time   Mean_Air_Temp Mean_Precip Total_Precip
1 Hungerford 2022-12-20 2023-03-20 -3.057136     0.0200301   173
  Observations
1 8637

In [3]:
# Import libraries
library(fs)

# Set directories
home_dir <- Sys.getenv("HOME")
repo_dir <- file.path(home_dir, "OneDrive/git-repos/LCBP-interannual-EMMAs")
source(file.path(repo_dir, "Functions/plot_winter_air_temps.R"))
data_dir <- file.path(repo_dir, "Data/") 

# Setup for Wade winter 2023
target_site <- "Wade"
target_start <- "12-20-2022 00:00:00"
target_end <- "03-20-2023 00:00:00"
wade_file <- file.path(data_dir, "Met_data", "wade_2020-2024_met_2024-11-08.csv") 

# Run for Wade winter 2023
wade_winter_stats <- calculate_met_stats(
  site_name = target_site,
  start_datetime = target_start,
  end_datetime = target_end,
  met_data_path = wade_file
)

# View the results
head(wade_winter_stats)

New names:
• `` -> `...1`

  Site Start_Time End_Time   Mean_Air_Temp Mean_Precip Total_Precip
1 Wade 2022-12-20 2023-03-20 -4.071767     0.02111844  182.4
  Observations
1 25713